swagger: "2.0"
info:
  description: "API pública del servicio de gestion de incidencias Willie"
  version: "1.0.0"
  title: "API Willie"
tags:
- name: "incidencia"
  description: "CRUD incidencias"
schemes:
- "http"
paths:
  /incidencia:
    post:
      tags:
      - "incidencia"
      summary: "Añade una nueva incidencia"
      description: "Añade una nueva incidencia en las coordenadas dadas"
      operationId: "añadeIncidencia"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Datos necesarios para crear una incidencia"
        required: true
        schema:
          $ref: "#/definitions/Incidencia"
      responses:
        405:
          description: "Invalid input"

securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Incidencia:
    type: "object"
    properties:
      latitud:
        type: "number"
        format: "float64"
      longitud:
        type: "number"
        format: "float64"
      descripcion:
        type: "string"
        example: "luz fundida"
      notificacion:
        type: "boolean"
        description: "Es notificación general"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
